"""Compact, simulator-independent contracts for action-verifier datasets."""

from latentguard.action_verifier.identity import (
    ASSIGNMENT_ID_PREFIX,
    DATASET_DIGEST_PREFIX,
    GROUP_ID_PREFIX,
    SAMPLE_ID_PREFIX,
    SPLIT_POLICY_ID_PREFIX,
    compute_action_verifier_dataset_digest,
    compute_action_verifier_sample_identifier,
    compute_candidate_group_identifier,
    compute_split_assignment_identifier,
    compute_split_policy_identifier,
)
from latentguard.action_verifier.models import (
    ACTION_VERIFIER_SCHEMA_VERSION,
    FIXED_ACTION_CHUNK_HORIZON,
    ActionVerifierCandidateGroupV1,
    ActionVerifierDatasetV1,
    ActionVerifierSampleV1,
    CandidateType,
    DatasetSplit,
    TrajectorySplitAssignmentV1,
)
from latentguard.action_verifier.serialization import (
    MANIFEST_NAME,
    SERIALIZATION_FORMAT,
    SERIALIZATION_VERSION,
    ActionVerifierSerializationError,
    UnsupportedActionVerifierSerializationVersionError,
    load_action_verifier_dataset,
    save_action_verifier_dataset,
)
from latentguard.action_verifier.splits import (
    FULL_SPLIT_COUNTS,
    SplitLeakageError,
    TrajectorySplitSourceV1,
    assign_trajectory_splits,
    validate_no_split_leakage,
)
from latentguard.action_verifier.validation import (
    ActionVerifierValidationError,
    validate_action_verifier_candidate_group,
    validate_action_verifier_dataset,
    validate_action_verifier_evidence_references,
    validate_action_verifier_sample,
    validate_trajectory_split_assignment,
)

__all__ = [
    "ACTION_VERIFIER_SCHEMA_VERSION",
    "ASSIGNMENT_ID_PREFIX",
    "DATASET_DIGEST_PREFIX",
    "FIXED_ACTION_CHUNK_HORIZON",
    "FULL_SPLIT_COUNTS",
    "GROUP_ID_PREFIX",
    "MANIFEST_NAME",
    "SAMPLE_ID_PREFIX",
    "SERIALIZATION_FORMAT",
    "SERIALIZATION_VERSION",
    "SPLIT_POLICY_ID_PREFIX",
    "ActionVerifierCandidateGroupV1",
    "ActionVerifierDatasetV1",
    "ActionVerifierSampleV1",
    "ActionVerifierSerializationError",
    "ActionVerifierValidationError",
    "CandidateType",
    "DatasetSplit",
    "SplitLeakageError",
    "TrajectorySplitAssignmentV1",
    "TrajectorySplitSourceV1",
    "UnsupportedActionVerifierSerializationVersionError",
    "assign_trajectory_splits",
    "compute_action_verifier_dataset_digest",
    "compute_action_verifier_sample_identifier",
    "compute_candidate_group_identifier",
    "compute_split_assignment_identifier",
    "compute_split_policy_identifier",
    "load_action_verifier_dataset",
    "save_action_verifier_dataset",
    "validate_action_verifier_candidate_group",
    "validate_action_verifier_dataset",
    "validate_action_verifier_evidence_references",
    "validate_action_verifier_sample",
    "validate_no_split_leakage",
    "validate_trajectory_split_assignment",
]
